language: emacs-lisp
env:
  - EMACS=emacs-snapshot
before_install:
  # Nightly Emacs snapshot builds
  - sudo add-apt-repository -y ppa:ubuntu-elisp/ppa
  # Update and install the Emacs for our environment
  - sudo apt-get update -qq
  - sudo apt-get install -qq -yy ${EMACS}-nox
  # Install and bootstrap cask
  - curl -fsSL https://raw.githubusercontent.com/cask/cask/master/go | python
  - export PATH="${HOME}/.cask/bin:$PATH"
install:
  - cask --debug --verbose install
script:
  - make compile test
